Faset/Faset/Models/ErrorViewModel.cs
using System;

namespace Faset.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Faset/Faset/Models/Facet/BookListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faset.Models.Facet
{
    public class BookListViewModel
    {
        public IEnumerable<BookViewModel> Books { get; set; }
    }
}

Faset/Faset/Models/Facet/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faset.Models.Facet
{
    public class BookViewModel
    {
        public string Name { get; set; }
        public string Author { get; set; }
        public double? Price { get; set; }
        public string Discription { get; set; }
        public string Language { get; set; }
        public string Year { get; set; }
        public string Sales_note { get; set; }
    }
}

Faset/Faset/Models/Facet/PageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faset.Models.Facet
{
    public class PageViewModel
    {
        public IEnumerable<string> Languages { get; set; }
        public IEnumerable<string> Sales_notes { get; set; }
        //public IEnumerable<string> Publishers { get; set; }
        //public IEnumerable<string> Authors { get; set; }
    }
}

Faset/Faset/Models/FacetMenuModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faset.Models
{
    public class FacetMenuModel
    {
        public IEnumerable<string> Languages { get; set; }
        public IEnumerable<string> Sales_notes { get; set; }
        public IEnumerable<string> Publishers { get; set; }
        public IEnumerable<string> Authors { get; set; }
    }
}

Faset/Faset/Models/FasetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faset.Models
{
    public class FasetViewModel
    {
        public string Name { get; set; }
        public string Author { get; set; }
        public double? Price { get; set; }
        public string Discription { get; set; }
        public string Language { get; set; }
        public string Year { get; set; }
    }
}

Faset/Faset/Controllers/FacetController.cs
using Faset.Models.Facet;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Faset.Controllers
{
    public class FacetController : Controller
    {
        private readonly BookService bookService = new BookService();

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BooksPage()
        {
            return View(new PageViewModel {
                Languages = bookService.GetLanguages(),
                Sales_notes = bookService.GetSales_note()
            });
        }
        public IActionResult GetBooks(string Languages,string Sales_notes,int priceMin,int priceMax)
        {
            return View(new BookListViewModel
            {
                Books = bookService.GetBooksFaceted(Languages, Sales_notes,priceMin,priceMax).Take(10).Select(x =>
                   new BookViewModel
                   {
                       Name = x?.name,
                       Author = x?.name,
                       Discription = x?.description,
                       Language = x?.language?.name,
                       Price = x?.price,
                       Year = x?.year,
                       Sales_note = x?.sales_notes?.name
                   })
            });
        }
    }
}

Faset/Faset/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Faset.Models;

namespace Faset.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Faset/Faset/Views/Facet/BooksPage.cshtml
@model Faset.Models.Facet.PageViewModel

@{
    ViewData["Title"] = "Books";
}

<h2>View</h2>

<div class="row">
    <div id="facet-menu" class="col-md-2 facet-menu">
        <h4>Choose Language</h4>
        @foreach (var task in Model.Languages)
        {
            <div class="form-check">
                <input class="form-check-input facet-language" type="checkbox" value="@task" id="@task">
                <label class="form-check-label" for="@task">
                    @task
                </label>
            </div>
        }
        <h4>Choose sales notes</h4>
        @foreach (var task in Model.Sales_notes)
        {
            <div class="form-check">
                <input class="form-check-input facet-sales_notes" type="checkbox" value="@task" id="@task">
                <label class="form-check-label" for="@task">
                    @task
                </label>
            </div>
        }
        <label class="form-check-label" for="">
            Filter by price interval:
        </label>
        <b>€ 0</b> 
        <input id="ex2" type="text" class="span2 form-check-input" value="" data-slider-min="0" data-slider-max="5000" data-slider-step="20" data-slider-value="[0,5000]" />
        <b>€ 5000</b>

    </div>
    <div id="books-content" class="col-md-10">  </div>
</div>
@section Scripts {
    <script>
        $(document).ready(function () {
            console.log('Init GetBooks');
            GetBooksAjax('', '',0,@int.MaxValue);
            $("#ex2").slider({});
        });
        function GetBooksAjax(languages, sales_notes,priceMin,priceMax) {
            $('#books-content').load(
                url = '/Facet/GetBooks/',
                data = 'languages=' + languages + '&Sales_notes=' + sales_notes + '&PriceMin=' + priceMin +'&PriceMax='+priceMax,
                success = function (data) {
                    console.log(data);
                }
            )
        }
        $('.form-check-input').on("change", function () {
            console.log('Init GetBooks');
            var Languages = getValueUsingClassLanguages();
            var salesNotes = getValueUsingClassSales_notes();
            var price = $("#ex2").val().split(',');
            console.log('Lan = ' + Languages + 'Sale = ' + salesNotes + 'Min = ' + price[0] + 'Max = ' + price[1]);
            GetBooksAjax(Languages, salesNotes,price[0],price[1]);
        })


        function getValueUsingClassSales_notes() {
            /* declare an checkbox array */
            var chkArray = [];

            /* look for all checkboes that have a class 'chk' attached to it and check if it was checked */
            $(".facet-sales_notes:checked").each(function () {
                chkArray.push($(this).val());
            });

            /* we join the array separated by the comma */
            var selected;
            selected = chkArray.join('|');

            return selected;
        }
        function getValueUsingClassLanguages() {
            /* declare an checkbox array */
            var chkArray = [];

            /* look for all checkboes that have a class 'chk' attached to it and check if it was checked */
            $(".facet-language:checked").each(function () {
                chkArray.push($(this).val());
            });

            /* we join the array separated by the comma */
            var selected;
            selected = chkArray.join('|');

            return selected;
        }
    </script>
}

Faset/Faset/Views/Facet/GetBooks.cshtml
@model Faset.Models.Facet.BookListViewModel
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Language</th>
            <th>Sales_note</th>
            <th>Year</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model.Books)
            {
                <tr>
                    <td>
                        @book.Name
                    </td>
                    <td>
                        @book.Price
                    </td>
                    <td>
                        @book.Language
                    </td>
                    <td>
                        @book.Sales_note
                    </td>
                    <td>
                        @book.Year
                    </td>
                </tr>
            }
    </tbody>
</table>

Faset/Faset/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Faset/Faset/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Faset/Faset/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Faset/Faset/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Facet</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/bootstrap-slider.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        @*<link rel="stylesheet" href="~/css/bootstrap-slider.css" asp-append-version="true" />*@
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Faset</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Facet" asp-action="BooksPage">Book list</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Faset</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/bootstrap-slider.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        @*<script src="~/js/bootstrap-slider.js" asp-append-version="true"></script>*@
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>